
import { Vehicle } from '../types';

export const VEHICLES: Vehicle[] = [
  {
    id: 'camry',
    name: 'Camry Hybrid',
    tagline: 'The Pinnacle of Sustainable Luxury',
    type: 'Sedan',
    priceRange: '₹ 46.17 Lakh',
    mileage: '19.1 kmpl',
    engine: '2.5L 4-Cylinder Hybrid',
    horsepower: '218 HP',
    torque: '221 Nm',
    fuelType: 'Petrol Hybrid',
    seatingCapacity: 5,
    bannerImage: '/assets/banner1.jpg',
    mainImage: '/assets/cars/camry-main.webp',
    exteriorImage: '/assets/cars/camry-ext.webp',
    interiorImage: '/assets/cars/camry-int.webp',
    gallery: ['/assets/cars/camry-1.webp', '/assets/cars/camry-2.webp'],
    description: 'The All New Camry HEV is a masterpiece of intelligent engineering, offering a seamless blend of luxury and environmental consciousness.',
    longDescription: 'The Toyota Camry Hybrid stands alone as the executive sedan of choice for leaders across the globe. Built on the TNGA platform, it offers an exceptionally stable and refined ride quality. In the context of New Delhi, where air quality and traffic congestion are constant considerations, the Camry\'s Strong Hybrid technology offers a future-proof mobility solution. It is not just a car; it is a statement of intent—proving that high-performance luxury can coexist with responsible carbon management. For the discerning buyer at Galaxy Toyota, the Camry offers an unparalleled ownership experience backed by decades of hybrid leadership.',
    interiorDescription: 'A sanctuary of silence. Featuring power-reclining rear seats, 3-zone climate control, and a premium 9-speaker JBL audio system. The cabin isolation is a benchmark in its class, ensuring that the bustle of NCR traffic never enters your private space. Every material, from the Y-design dashboard garnish to the high-grade leather upholstery, is chosen for its longevity and aesthetic appeal.',
    exteriorDescription: 'Aerodynamic elegance meets authoritative presence. The wide stance, sharp LED headlamps with signature DRLs, and the sophisticated silhouette ensure the Camry commands attention at every business arrival. Functional elements like the lower grille design and side air-intakes optimize airflow for better stability and cooling.',
    performanceDescription: 'The 2.5L Dynamic Force engine paired with a high-output electric motor delivers 218 combined HP. Acceleration is instantaneous and gearless thanks to the electronically controlled CVT (e-CVT). Drive modes allow you to switch between EV, Eco, Normal, and Sport, tailoring the powertrain to the specific demands of your journey.',
    safetyDescription: 'Uncompromised protection with 9 SRS Airbags as standard. Advanced active safety features include Vehicle Stability Control (VSC), Traction Control (TRC), and Hill Start Assist. The Camry is a fortress on wheels, designed to protect its occupants with the highest level of automotive engineering.',
    features: ['Reclining Rear Seats', '3-Zone AC', 'Memory Seats', '9 Airbags', 'JBL Audio', 'Ventilated Front Seats'],
    safetyFeatures: ['9 SRS Airbags', 'VSC with Brake Assist', 'Hill Start Assist', 'ISOFIX Child Seat Mounts', 'Parking Sensors with Camera'],
    variants: [{ name: '2.5 Hybrid AT', price: '₹46.17 Lakh', engine: '2.5L Hybrid', transmission: 'e-CVT', features: ['Fully Loaded'] }]
  },
  {
    id: 'fortuner',
    name: 'Fortuner',
    tagline: 'Lead The Charge with Authority',
    type: 'SUV',
    priceRange: '₹ 33.43 - 51.44 Lakh',
    mileage: '14.2 kmpl',
    engine: '2.8L Diesel / 2.7L Petrol',
    horsepower: '201 HP',
    torque: '500 Nm',
    fuelType: 'Diesel/Petrol',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/fortuner-banner.webp',
    mainImage: '/assets/cars/fortuner-main.webp',
    exteriorImage: '/assets/cars/fortuner-ext.webp',
    interiorImage: '/assets/cars/fortuner-int.webp',
    gallery: ['/assets/cars/fortuner-1.webp'],
    description: 'The undisputed king of the premium SUV segment in India, known for its bulletproof reliability.',
    longDescription: 'For over a decade, the Fortuner has been the definitive symbol of power on Indian roads. Engineered to conquer everything from the highways of Haryana to the rocky trails of the Himalayas, its legendary 4x4 capability is matched only by its commanding road presence. At Galaxy Toyota, we understand that a Fortuner owner seeks absolute authority and peace of mind—qualities that this vehicle delivers in every single drive.',
    interiorDescription: 'Premium all-black leather upholstery with ventilated front seats for maximum comfort during long NCR summers. The 11-speaker JBL audio system and large touchscreen infotainment ensure that every long drive is as entertaining as it is authoritative. The modular seating allows for versatile cargo configurations, perfect for family expeditions.',
    exteriorDescription: 'Quad-LED headlamps, an aggressive front grille, and 18-inch chrome-finished alloy wheels define its high-status look. The high ground clearance and muscular fenders are not just for show; they reflect a true body-on-frame SUV pedigree that can handle the toughest terrains with ease.',
    performanceDescription: 'The 2.8L Diesel engine is a powerhouse, delivering a massive 500 Nm of torque. Combined with Active Traction Control and a sophisticated 4WD system with Electronic Drive Control, the Fortuner offers total dominance in any driving condition.',
    safetyDescription: '7 SRS Airbags, Vehicle Stability Control (VSC) with Brake Assist, and Hill Start Assist Control (HAC) ensure that your power is always under control. The high-strength impact-absorbing body (GOA) provides a safe shell for all occupants.',
    features: ['4x4 System', 'Ventilated Seats', 'JBL Audio', 'Kick Sensor Boot', 'Dual Zone AC'],
    safetyFeatures: ['7 SRS Airbags', 'Active Traction Control', 'Dac (Downhill Assist Control)', 'VSC with BA', 'HAC'],
    variants: [
      { name: '2.7L Petrol 4x2 MT', price: '₹33.43 Lakh', engine: '2.7L Petrol', transmission: 'Manual', features: ['Standard SUV Kit'] },
      { name: '2.8L Diesel 4x4 AT', price: '₹42.32 Lakh', engine: '2.8L Diesel', transmission: 'Automatic', features: ['4WD Mastery'] }
    ]
  },
  {
    id: 'hycross',
    name: 'Innova Hycross',
    tagline: 'Experience The Future of Family Luxury',
    type: 'MPV',
    priceRange: '₹ 19.77 - 30.98 Lakh',
    mileage: '23.24 kmpl',
    engine: '2.0L TNGA 5th Gen Hybrid',
    horsepower: '184 HP',
    torque: '206 Nm',
    fuelType: 'Petrol Hybrid',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/hycross-banner.webp',
    mainImage: '/assets/cars/hycross-main.webp',
    exteriorImage: '/assets/cars/hycross-ext.webp',
    interiorImage: '/assets/cars/hycross-int.webp',
    gallery: ['/assets/cars/hycross-1.webp'],
    description: 'The All New Innova Hycross is a perfect blend of SUV stance and the luxury of an executive lounge.',
    longDescription: 'The Hycross redefines family mobility for the modern era. Built on the TNGA-C monocoque platform, it offers car-like handling, exceptional ride comfort, and a level of efficiency that was previously unthinkable in this segment. As India\'s favorite people-mover in its most advanced avatar, it caters to the high-net-worth individual who values space, tech, and the environmental benefits of hybrid propulsion.',
    interiorDescription: 'Featuring the legendary Ottoman seats with power-recline and footrests in the second row. A massive panoramic sunroof, multi-zone climate control, and mood lighting create a first-class travel experience for the entire family. The dashboard is modern and tech-forward, featuring a 10.1-inch floating display and premium materials throughout.',
    exteriorDescription: 'Muscular SUV-inspired styling with a bold hexagonal grille and sharp LED headlamps. The 18-inch alloy wheels and wide stance give it a commanding presence that blurs the lines between an MPV and a luxury SUV. Aerodynamic fins and a sleek roofline contribute to its class-leading efficiency.',
    performanceDescription: 'The 5th Gen Self-Charging Strong Hybrid system delivers silent, smooth, and powerful performance. With a combined 186 PS of power, it handles full loads with ease while returning an incredible 23.24 kmpl in city conditions.',
    safetyDescription: 'Equipped with Toyota Safety Sense (TSS) 3.0, offering Dynamic Radar Cruise Control, Lane Trace Assist, and Blind Spot Monitor. With 6 SRS airbags and all-wheel disc brakes, safety is at the core of the Hycross DNA.',
    features: ['Ottoman Seats', 'Panoramic Sunroof', 'TSS 3.0', 'Hybrid Powertrain', '360 Camera'],
    safetyFeatures: ['6 SRS Airbags', 'Dynamic Radar Cruise Control', 'Lane Trace Assist', 'Blind Spot Monitor', 'All Wheel Disc Brakes'],
    variants: [
      { name: 'GX Petrol', price: '₹19.77 Lakh', engine: '2.0L Petrol', transmission: 'CVT', features: ['Entry Luxury'] },
      { name: 'ZX Hybrid', price: '₹30.68 Lakh', engine: '2.0L Hybrid', transmission: 'e-CVT', features: ['Fully Loaded Hybrid'] }
    ]
  },
  {
    id: 'lc300',
    name: 'Land Cruiser 300',
    tagline: 'The Absolute King of Earth',
    type: 'Luxury',
    priceRange: '₹ 2.10 Cr',
    mileage: '10.0 kmpl',
    engine: '3.3L V6 Twin-Turbo Diesel',
    horsepower: '304 HP',
    torque: '700 Nm',
    fuelType: 'Diesel',
    seatingCapacity: 5,
    bannerImage: '/assets/banner4.jpg',
    mainImage: '/assets/cars/lc300-main.webp',
    exteriorImage: '/assets/cars/lc300-ext.webp',
    interiorImage: '/assets/cars/lc300-int.webp',
    gallery: ['/assets/cars/lc300-1.webp', '/assets/cars/lc300-2.webp'],
    description: 'Iconic dominance for over 70 years. The LC300 is the ultimate expression of luxury and capability.',
    longDescription: 'The Land Cruiser 300 is not just a vehicle; it is a global icon of authority. Built on the new GA-F platform, it maintains its traditional body-on-frame structure while reducing weight and improving rigidity. For those in Delhi NCR who demand the absolute pinnacle of automotive prestige, the LC300 offers a presence that is unmatched by any other SUV on the planet.',
    interiorDescription: 'A sanctuary of world-class luxury. 12.3-inch infotainment, 14-speaker JBL audio, and fingerprint authentication for the engine start. The heated and ventilated seats ensure total comfort in extreme climates, from the deserts of Rajasthan to the peaks of Ladakh.',
    exteriorDescription: 'Massive front grille, triple-LED headlamps, and 20-inch alloy wheels. Its ground clearance and approach angles are optimized for conquering the world\'s toughest terrains while maintaining a high-status look for city arrivals.',
    performanceDescription: 'V6 Twin-Turbo producing 700 Nm of torque for total dominance. The E-KDSS (Electronic Kinetic Dynamic Suspension System) ensures exceptional on-road comfort and world-class off-road articulation.',
    safetyDescription: '10 SRS Airbags and the most advanced Toyota Safety Sense suite. Pre-collision systems, lane departure alerts, and adaptive high beams provide a fortress of safety for its occupants.',
    features: ['E-KDSS', 'Multi Terrain Monitor', 'Fingerprint Auth', '12.3-inch Display', '14 JBL Speakers'],
    safetyFeatures: ['10 SRS Airbags', 'Adaptive High Beam System', 'Lane Departure Alert', 'TSS 3.0', 'Multi Terrain Select'],
    variants: [{ name: 'ZX Diesel', price: '₹2.10 Cr', engine: '3.3L V6', transmission: 'Automatic', features: ['Absolute Luxury'] }]
  },
  {
    id: 'hilux',
    name: 'Hilux',
    tagline: 'Adventure Accomplished. Unbreakable Heritage.',
    type: 'Pickup',
    priceRange: '₹ 30.40 - 37.90 Lakh',
    mileage: '12.0 kmpl',
    engine: '2.8L Turbo Diesel',
    horsepower: '201 HP',
    torque: '500 Nm',
    fuelType: 'Diesel',
    seatingCapacity: 5,
    bannerImage: '/assets/banner3.jpg',
    mainImage: '/assets/cars/hilux-main.webp',
    exteriorImage: '/assets/cars/hilux-ext.webp',
    interiorImage: '/assets/cars/hilux-int.webp',
    gallery: ['/assets/cars/hilux-1.webp'],
    description: 'The world legend of toughness. A lifestyle pickup that conquers every challenge.',
    longDescription: 'The Hilux is the world\'s most famous pickup for a reason. Its indestructible reputation has been earned over decades in the most hostile environments. In India, it serves as the ultimate lifestyle utility vehicle—perfect for the adventure-seeker who wants a vehicle that can carry their gear on weekends and cruise comfortably on weekdays.',
    interiorDescription: 'Durable yet premium. Leather-wrapped cabin with 8-inch touchscreen and dual-zone AC. The seating is ergonomically designed to support occupants over long, rough journeys.',
    exteriorDescription: 'Muscular body lines, 18-inch alloys, and a rear deck built for heavy-duty hauling. The heavy-duty chassis and impact-absorbing body make it the toughest pickup in the world.',
    performanceDescription: 'Active Traction Control and high-wading depth of 700mm. The 500Nm torque engine ensures you never run out of breath on steep inclines or with heavy loads.',
    safetyDescription: '7 Airbags, Vehicle Stability Control, and ABS with EBD come standard, ensuring safety on trails and highways alike.',
    features: ['4x4 System', '700mm Wading', 'Heavy Duty Chassis', 'Leather Cabin', '8-inch Touchscreen'],
    safetyFeatures: ['7 SRS Airbags', 'VSC with BA', 'Hill Start Assist', 'Electronic Drive Control', 'ABS with EBD'],
    variants: [{ name: 'Standard MT', price: '₹30.40 Lakh', engine: '2.8L Diesel', transmission: 'Manual', features: ['4WD Essential'] }]
  },
  {
    id: 'taisor',
    name: 'Urban Cruiser Taisor',
    tagline: 'Go Daringly Dark. Make Your Way.',
    type: 'SUV',
    priceRange: '₹ 7.74 - 13.04 Lakh',
    mileage: '22.8 kmpl',
    engine: '1.0L Turbo / 1.2L Petrol',
    horsepower: '100 HP',
    torque: '148 Nm',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    bannerImage: '/assets/banner5.jpg',
    mainImage: '/assets/cars/taisor-main.webp',
    exteriorImage: '/assets/cars/taisor-ext.webp',
    interiorImage: '/assets/cars/taisor-int.webp',
    gallery: ['/assets/cars/taisor-1.webp'],
    description: 'A stylish crossover designed for the modern urban explorer who demands flair and performance.',
    longDescription: 'The Taisor is Toyota\'s latest answer to the sub-compact SUV segment. Blending SUV styling with compact agility, it is the perfect vehicle for navigating the busy streets of Delhi and Noida. Its turbocharged engine options and premium interior make it an attractive choice for young professionals.',
    interiorDescription: 'Premium dual-tone interior with 9-inch Smart Playcast and wireless charger. The Head-Up Display (HUD) and 360-degree camera make navigating urban environments effortless.',
    exteriorDescription: 'Bold crossover styling with twin-slat chrome grille and sporty bumpers. The aero-inspired design is complemented by 16-inch diamond-cut alloy wheels.',
    performanceDescription: 'Experience the thrill of the 1.0L Turbocharged engine producing 100 HP. For those who prioritize efficiency, the 1.2L naturally aspirated engine offers a smooth and refined driving experience.',
    safetyDescription: '6 Airbags, ESP with Hill Hold, and a 360-degree camera provide a safety net for city driving.',
    features: ['Turbo Engine', '360 Camera', 'HUD', '9-inch Touch', 'Wireless Charger'],
    safetyFeatures: ['6 Airbags', 'Electronic Stability Program', 'Hill Hold Assist', 'ABS with EBD', 'Parking Sensors'],
    variants: [{ name: 'V Turbo AT', price: '₹13.04 Lakh', engine: '1.0L Turbo', transmission: 'Automatic', features: ['Top Spec'] }]
  },
  {
    id: 'hyryder',
    name: 'Urban Cruiser Hyryder',
    tagline: 'The Hybrid Life. Efficiency Redefined.',
    type: 'SUV',
    priceRange: '₹ 11.14 - 20.19 Lakh',
    mileage: '27.97 kmpl',
    engine: '1.5L Self-Charging Hybrid',
    horsepower: '114 HP',
    torque: '122 Nm',
    fuelType: 'Petrol Hybrid',
    seatingCapacity: 5,
    bannerImage: '/assets/cars/hyryder-banner.webp',
    mainImage: '/assets/cars/hyryder-main.webp',
    exteriorImage: '/assets/cars/hyryder-ext.webp',
    interiorImage: '/assets/cars/hyryder-int.webp',
    gallery: ['/assets/cars/hyryder-1.webp'],
    description: 'India’s first strong hybrid SUV in its segment. Silent, smooth, and incredibly efficient.',
    longDescription: 'The Hyryder brings Toyota’s world-leading hybrid technology to the heart of the Indian SUV market. It is designed for those who want a premium SUV experience without the high running costs or environmental impact of traditional engines. With its class-leading fuel efficiency, it is the ideal urban explorer.',
    interiorDescription: 'Sophisticated dual-tone dash with soft-touch materials. Features like a panoramic sunroof, ventilated front seats, and a 360-degree camera elevate the daily commute.',
    exteriorDescription: 'Elegant and sophisticated SUV design with a crystal acrylic grille and sleek LED signatures. The high hood line and muscular fenders give it a true SUV stance.',
    performanceDescription: 'Smooth e-CVT and silent hybrid powertrain. Switch to EV mode for a pure electric drive in stop-and-go traffic, maximizing efficiency and serenity.',
    safetyDescription: '6 SRS airbags, all-wheel disc brakes, and Vehicle Stability Control ensure that safety is never compromised.',
    features: ['360 Camera', 'Wireless Charging', 'Sunroof', 'Hybrid Tech', 'Ventilated Seats'],
    safetyFeatures: ['6 SRS Airbags', 'All Wheel Disc Brakes', 'VSC', 'TPMS', 'Hill Hold Assist'],
    variants: [{ name: 'V Hybrid AT', price: '₹20.19 Lakh', engine: '1.5L Hybrid', transmission: 'e-CVT', features: ['Strong Hybrid'] }]
  },
  {
    id: 'glanza',
    name: 'Glanza',
    tagline: 'Hatchin’ Awesome. The Tech-Loaded Hatch.',
    type: 'Hatchback',
    priceRange: '₹ 6.86 - 10.00 Lakh',
    mileage: '22.35 kmpl',
    engine: '1.2L Dual Jet Petrol',
    horsepower: '89 HP',
    torque: '113 Nm',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    bannerImage: '/assets/cars/glanza-banner.webp',
    mainImage: '/assets/cars/glanza-main.webp',
    exteriorImage: '/assets/cars/glanza-ext.webp',
    interiorImage: '/assets/cars/glanza-int.webp',
    gallery: ['/assets/cars/glanza-1.webp'],
    description: 'The cool hatchback for the modern world. Loaded with tech, safety, and incredible efficiency.',
    longDescription: 'The Glanza is for the young and the young-at-heart. It redefines the premium hatchback segment by offering features like a Head-Up Display and 360-degree camera usually reserved for luxury sedans. It is the perfect first car for a modern Indian family.',
    interiorDescription: 'Modern and connected cabin with a 9-inch Smart Playcast. The HUD provides vital info without needing to look away from the road, while "Hey Toyota" voice assist keeps you in control.',
    exteriorDescription: 'Sporty liquid flow design with LED headlamps and signature DRLs. Stylish 16-inch alloy wheels and sleek lines make it stand out in the urban landscape.',
    performanceDescription: 'Refined 1.2L engine with idle start-stop technology to save fuel in heavy traffic. Available in both Manual and AMT transmissions.',
    safetyDescription: '6 Airbags and a 360-degree camera come standard on top variants, offering segment-leading safety and confidence.',
    features: ['HUD', '360 Camera', '9-inch Screen', '6 Airbags', 'Voice Assist'],
    safetyFeatures: ['6 SRS Airbags', 'ABS with EBD', 'Brake Assist', 'ESP with Hill Hold', '360 Camera'],
    variants: [{ name: 'V AMT', price: '₹10.00 Lakh', engine: '1.2L Petrol', transmission: 'AMT', features: ['Fully Loaded'] }]
  }
];
