
import { Vehicle } from '../types';

export const VEHICLES: Vehicle[] = [
  {
    id: 'camry',
    name: 'Camry Hybrid',
    tagline: 'The Art of Hybrid Luxury',
    type: 'Sedan',
    priceRange: '₹ 46.17 Lakh',
    mileage: '19.1 kmpl',
    engine: '2.5L 4-Cylinder Hybrid',
    horsepower: '218 HP',
    torque: '221 Nm',
    fuelType: 'Petrol Hybrid',
    seatingCapacity: 5,
    bannerImage: '/assets/banner1.jpg',
    mainImage: '/assets/cars/camry-main.webp',
    exteriorImage: '/assets/cars/camry-ext.webp',
    interiorImage: '/assets/cars/camry-int.webp',
    gallery: ['/assets/cars/camry-1.webp', '/assets/cars/camry-2.webp'],
    description: 'The New Camry HEV is a masterpiece of intelligent engineering, combining high-end luxury with an eco-conscious hybrid powertrain.',
    longDescription: 'The Toyota Camry Hybrid stands as the pinnacle of executive sedans in India. Built on the TNGA (Toyota New Global Architecture) platform, it offers an unparalleled balance of stability, agility, and ride comfort. As a Self-Charging Strong Hybrid Electric Vehicle (SHEV), it allows you to enjoy quiet, emission-free drives in EV mode while delivering powerful performance on the highway. It remains the preferred choice for diplomats and industry leaders who value sophistication and world-class reliability.',
    interiorDescription: 'Experience a sanctuary of silence and refinement. The cabin features power-reclining rear seats with a touch-control armrest, allowing passengers to adjust climate and audio settings effortlessly. The 3-zone independent air conditioning ensures personalized comfort, while the premium 9-speaker JBL audio system provides a concert-like experience. Wrapped in high-grade leather with exquisite Onyx garnish, every detail is crafted to provide a first-class travel experience.',
    exteriorDescription: 'Sleek, aerodynamic, and commanding. The Camry features a bold front grille with sharp LED headlamps and signature DRLs that exude a sophisticated road presence. Its low-slung silhouette is complemented by 18-inch multi-spoke alloy wheels, while the aerodynamic lines flow seamlessly from the aggressive front bumper to the elegant rear, optimizing both style and fuel efficiency.',
    performanceDescription: 'Equipped with a 2.5L Dynamic Force 4-Cylinder engine paired with a powerful electric motor, delivering a combined output of 218 HP. The electronically controlled Continuous Variable Transmission (e-CVT) ensures seamless gear shifts and instantaneous torque, making every drive smooth and responsive.',
    safetyDescription: 'Safety is uncompromised with 9 SRS Airbags, including front, side, curtain, and knee airbags. Advanced active safety features like Vehicle Stability Control (VSC), Traction Control (TRC), and Hill Start Assist Control (HAC) come standard, ensuring absolute control in every driving condition.',
    techDescription: 'The 9-inch touchscreen infotainment system supports seamless smartphone integration via Apple CarPlay and Android Auto. A 10-inch color Head-Up Display (HUD) keeps vital information directly in your line of sight, while the 7-inch TFT multi-information display provides real-time hybrid system monitoring.',
    drivingExperience: 'A smooth, gliding ride quality that irons out Indian road imperfections with ease. The hybrid system automatically manages power between the engine and motor for maximum efficiency without requiring external charging.',
    ownershipBenefits: ['8 Year / 1,60,000 km Hybrid Battery Warranty', '3 Year / 1,00,000 km Standard Warranty', 'Toyota Q Service Support at Galaxy Hubs'],
    features: ['Power Reclining Rear Seats', '3-Zone Climate Control', 'JBL Premium Sound', 'Memory Driver Seat', 'Sunroof'],
    variants: [{ name: '2.5 Hybrid AT', price: '₹46.17 Lakh', engine: '2.5L Hybrid', transmission: 'e-CVT', features: ['Full Loaded Luxury'] }]
  },
  {
    id: 'lc300',
    name: 'Land Cruiser 300',
    tagline: 'The King of All Terrains',
    type: 'Luxury',
    priceRange: '₹ 2.10 Cr',
    mileage: '10.0 kmpl',
    engine: '3.3L V6 Twin-Turbo Diesel',
    horsepower: '304 HP',
    torque: '700 Nm',
    fuelType: 'Diesel',
    seatingCapacity: 5,
    bannerImage: '/assets/banner4.jpg',
    mainImage: '/assets/cars/lc300-main.webp',
    exteriorImage: '/assets/cars/lc300-ext.webp',
    interiorImage: '/assets/cars/lc300-int.webp',
    gallery: ['/assets/cars/lc300-1.webp', '/assets/cars/lc300-2.webp'],
    description: 'Built on a 70-year legacy of dominance, the LC300 is the ultimate expression of durability and prestige.',
    longDescription: 'The Land Cruiser 300 is engineered to conquer the most hostile environments on Earth while providing a world-class luxury experience. Built on the new GA-F platform, it maintains its traditional body-on-frame structure but with significant weight reduction and improved rigidity. It is not just an SUV; it is a global icon of authority and reliability, trusted by adventurers and dignitaries across the planet.',
    interiorDescription: 'Unrivaled luxury meets functionality. The cabin features a massive 12.3-inch infotainment system, a 14-speaker JBL audio system, and fingerprint-authenticated engine start for enhanced security. Heated and ventilated seats for both front and rear rows ensure comfort in extreme climates, from the scorching heat of Delhi to the freezing peaks of Leh.',
    exteriorDescription: 'A commanding presence with its signature massive grille and unique Triple-Beam LED headlamps. The aluminum body panels reduce weight by 200kg, lowering the center of gravity and improving handling. The iconic SUV silhouette remains, signaling its indestructible Toyota QDR pedigree.',
    performanceDescription: 'The 3.3L V6 Twin-Turbo Diesel engine produces a staggering 700 Nm of torque, ensuring effortless power delivery. The advanced 10-speed automatic transmission and E-KDSS (Electronic Kinetic Dynamic Suspension System) provide unparalleled wheel articulation off-road and rock-solid stability on-road.',
    safetyDescription: 'Toyota Safety Sense suite includes Pre-Collision System, Lane Trace Assist, and Dynamic Radar Cruise Control. With 10 SRS Airbags and a reinforced chassis, the LC300 provides a fortress of safety for its occupants.',
    techDescription: 'The Multi-Terrain Monitor with Underfloor View allows drivers to see obstacles directly beneath the tires, making rocky trails effortless to navigate. Global connected services keep you in touch with your vehicle anywhere.',
    drivingExperience: 'Commanding and indestructible. You sit high with a clear view of the horizon, feeling the sheer mass and quality of a vehicle that is built to last for generations.',
    ownershipBenefits: ['Global Warranty Support', 'Premium Concierge Service at Galaxy Okhla', 'Highest Potential Resale Value'],
    features: ['E-KDSS Suspension', 'Multi Terrain Monitor', 'Fingerprint Authentication', '12.3-inch Display'],
    variants: [{ name: 'ZX Diesel', price: '₹2.10 Cr', engine: '3.3L V6', transmission: '10-Speed AT', features: ['Full Global Spec'] }]
  },
  {
    id: 'hilux',
    name: 'Hilux',
    tagline: 'Adventure Accomplished',
    type: 'Pickup',
    priceRange: '₹ 30.40 - 37.90 Lakh',
    mileage: '12.0 kmpl',
    engine: '2.8L Turbo Diesel',
    horsepower: '201 HP',
    torque: '500 Nm',
    fuelType: 'Diesel',
    seatingCapacity: 5,
    bannerImage: '/assets/banner3.jpg',
    mainImage: '/assets/cars/hilux-main.webp',
    exteriorImage: '/assets/cars/hilux-ext.webp',
    interiorImage: '/assets/cars/hilux-int.webp',
    gallery: ['/assets/cars/hilux-1.webp'],
    description: 'The world legend of toughness. A lifestyle utility vehicle that bridges the gap between rugged workhorse and premium SUV.',
    longDescription: 'Indestructible quality meets modern sophistication. The Hilux is built for the adventurous who demand a vehicle as resilient as they are. With its legendary 4x4 pedigree and a high-payload deck, it is as much a reliable work partner as it is a leisure vehicle for weekend escapes. Tested in the harshest conditions from the North Pole to the Dakar Rally.',
    interiorDescription: 'Surprisingly refined and durable. The leather-wrapped cabin features an 8-inch touchscreen with smartphone connectivity, dual-zone climate control, and premium seating. The cabin isolation is exceptional for a pickup, providing car-like comfort even on rough trails.',
    exteriorDescription: 'Muscular body lines, 18-inch alloy wheels, and a signature heavy-duty front grille. The rear deck is built for heavy-duty hauling, supported by a high-strength chassis that has earned the Hilux its "Unbreakable" reputation worldwide.',
    performanceDescription: 'Powered by the same 2.8L engine as the Fortuner, it delivers 500Nm of torque for total dominance. Features include a 4x4 system with Electronic Drive Control, Active Traction Control, and a high-wading depth of 700mm.',
    safetyDescription: '7 SRS Airbags, Vehicle Stability Control (VSC), and Hill Start Assist. The impact-absorbing body structure ensures safety on both highways and treacherous off-road tracks.',
    techDescription: 'Electronic Differential Lock and Downhill Assist Control (DAC) provide precision control during extreme off-roading. The 8-inch display keeps you connected to your favorite apps.',
    drivingExperience: 'A raw, powerful drive that feels unstoppable. The suspension is specially tuned to handle heavy loads without compromising on ride comfort for the passengers.',
    ownershipBenefits: ['Low Cost of Maintenance', 'Unbeatable Build Quality', 'Ready-to-Modify Chassis for Overlanding'],
    features: ['4x4 with Diff Lock', '700mm Wading Depth', 'Leather Cabin', '8-inch Smart Playcast'],
    variants: [{ name: 'Standard MT', price: '₹30.40 Lakh', engine: '2.8L Diesel', transmission: 'Manual', features: ['High 4WD'] }]
  },
  {
    id: 'taisor',
    name: 'Urban Cruiser Taisor',
    tagline: 'Go Daringly Dark',
    type: 'SUV',
    priceRange: '₹ 7.74 - 13.04 Lakh',
    mileage: '22.8 kmpl',
    engine: '1.0L Turbo / 1.2L Petrol',
    horsepower: '100 HP',
    torque: '148 Nm',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    bannerImage: '/assets/banner5.jpg',
    mainImage: '/assets/cars/taisor-main.webp',
    exteriorImage: '/assets/cars/taisor-ext.webp',
    interiorImage: '/assets/cars/taisor-int.webp',
    gallery: ['/assets/cars/taisor-1.webp'],
    description: 'A stylish and powerful crossover designed for the young urban explorer who demands both flair and performance.',
    longDescription: 'The Urban Cruiser Taisor blends SUV styling with compact agility. Perfect for navigating the busy streets of Delhi and Noida, it offers a punchy turbocharged performance and a feature-rich cabin. It represents the modern Toyota—youthful, tech-savvy, and incredibly efficient.',
    interiorDescription: 'The premium dual-tone interior is centered around a 9-inch Smart Playcast system. Features like a Head-Up Display (HUD), wireless charger, and a 360-degree camera make navigating urban environments effortless and safe.',
    exteriorDescription: 'Bold crossover styling with a twin-slat chrome grille, sporty bumpers, and unique LED signatures. The aero-inspired design is complemented by 16-inch diamond-cut alloy wheels and a sleek roofline that stands out in a crowd.',
    performanceDescription: 'Experience the thrill of the 1.0L Turbocharged engine producing 100 HP, or choose the refined 1.2L naturally aspirated engine for smooth city cruising. Both engines offer segment-leading fuel efficiency.',
    safetyDescription: 'Equipped with 6 Airbags, ESP with Hill Hold, and a 360-degree camera. The high-tensile steel body provides a solid safety foundation for city and highway driving.',
    techDescription: 'Toyota i-Connect offers 55+ features including remote AC control, live vehicle tracking, and smartwatch connectivity, ensuring you are always in control.',
    drivingExperience: 'Agile and easy to drive in heavy traffic with a light steering and responsive engine. The high ground clearance provides confidence on broken city roads.',
    ownershipBenefits: ['Best-in-class Fuel Efficiency', 'Low Cost of Ownership', 'Compact and Easy to Park'],
    features: ['Turbo Engine', '360 Camera', 'HUD', '9-inch Touch'],
    variants: [{ name: 'V Turbo AT', price: '₹13.04 Lakh', engine: '1.0L Turbo', transmission: 'Automatic', features: ['All-Tech Pack'] }]
  },
  {
    id: 'fortuner',
    name: 'Fortuner',
    tagline: 'The Undisputed King',
    type: 'SUV',
    priceRange: '₹ 33.43 - 51.44 Lakh',
    mileage: '14.2 kmpl',
    engine: '2.8L Diesel / 2.7L Petrol',
    horsepower: '201 HP',
    torque: '500 Nm',
    fuelType: 'Diesel/Petrol',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/fortuner-banner.webp',
    mainImage: '/assets/cars/fortuner-main.webp',
    exteriorImage: '/assets/cars/fortuner-ext.webp',
    interiorImage: '/assets/cars/fortuner-int.webp',
    gallery: ['/assets/cars/fortuner-1.webp'],
    description: 'Lead with power. The Fortuner is more than an SUV; it is a symbol of authority and unmatched reliability.',
    longDescription: 'For over a decade, the Fortuner has dominated the premium SUV segment in India. Engineered to conquer both the urban sprawl and the highest mountain passes, it is known for its bulletproof reliability and towering road presence. Whether it is a business meeting or a cross-country expedition, the Fortuner commands respect everywhere it goes.',
    interiorDescription: 'Premium all-black leather upholstery with ventilated front seats for maximum comfort during long summer drives. The 11-speaker JBL audio system and large touchscreen ensure every journey is entertaining. The cabin is spacious enough for 7 adults, with easy one-touch tumble seats for access to the third row.',
    exteriorDescription: 'Quad-LED headlamps and 18-inch chrome-finished alloy wheels. The aggressive front fascia, muscular fenders, and high ground clearance reflect its true off-road pedigree. Its timeless design ensures it remains the most desirable SUV in its class.',
    performanceDescription: 'The 2.8L Diesel engine is a powerhouse, producing 500 Nm of torque. With Active Traction Control and a sophisticated 4x4 system, it offers total dominance on any terrain. Driving modes (Eco/Normal/Sport) allow you to tailor the performance to your needs.',
    safetyDescription: '7 SRS Airbags and impact-absorbing GOA body ensure maximum occupant protection. Features like Vehicle Stability Control (VSC) with Brake Assist and Hill Start Assist come standard to keep you safe on and off the road.',
    techDescription: 'Connected car technology via Toyota i-Connect provides features like Geofencing, Vehicle Tracking, and SOS emergency alerts, keeping you connected to your vehicle at all times.',
    drivingExperience: 'Commanding and authoritative. You sit high with a clear view of the road, and the effortless power delivery makes highway overtakes a breeze.',
    ownershipBenefits: ['Highest Resale Value in India', 'Legendary Durability', 'Expert Service at Galaxy Platinum Hubs'],
    features: ['4x4 Capability', 'Ventilated Seats', 'JBL Audio', 'Kick Sensor Boot'],
    variants: [{ name: '2.8L 4x4 AT', price: '₹42.32 Lakh', engine: '2.8L Diesel', transmission: 'Automatic', features: ['4WD System'] }]
  },
  {
    id: 'hycross',
    name: 'Innova Hycross',
    tagline: 'Experience The Future of Luxury',
    type: 'MPV',
    priceRange: '₹ 19.77 - 30.98 Lakh',
    mileage: '23.24 kmpl',
    engine: '2.0L TNGA 5th Gen Hybrid',
    horsepower: '184 HP',
    torque: '206 Nm',
    fuelType: 'Petrol Hybrid',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/hycross-banner.webp',
    mainImage: '/assets/cars/hycross-main.webp',
    exteriorImage: '/assets/cars/hycross-ext.webp',
    interiorImage: '/assets/cars/hycross-int.webp',
    gallery: ['/assets/cars/hycross-1.webp'],
    description: 'The All New Innova Hycross is a perfect blend of SUV stance and the luxury comfort of a first-class lounge.',
    longDescription: 'The Innova Hycross redefines family travel. Built on the TNGA-C platform, it offers car-like handling with the massive space of a luxury MPV. As India’s favorite people mover in its new hybrid avatar, it delivers silent, smooth, and incredibly efficient performance that sets a new benchmark in the industry.',
    interiorDescription: 'The highlight is the Quilted Leather Ottoman Seats with power-recline and footrests in the middle row. Combined with a Panoramic Sunroof and multi-zone climate control, the Hycross creates an unparalleled travel experience for every family member.',
    exteriorDescription: 'Bold hexagonal grille and muscular SUV silhouette. Featuring 18-inch alloy wheels and sharp LED lighting signatures, the Hycross sheds the traditional MPV look for a more aggressive and premium road presence.',
    performanceDescription: 'The 5th Gen Self-Charging Strong Hybrid system delivers instant torque and silent acceleration. With a combined power of 186 PS, it offers effortless cruising while delivering an exceptional 23.24 kmpl mileage.',
    safetyDescription: 'Toyota Safety Sense 3.0 suite includes Dynamic Radar Cruise Control, Lane Trace Assist, and Blind Spot Monitor. With 6 SRS airbags and a high-strength chassis, safety is paramount.',
    techDescription: 'A 10.1-inch floating touchscreen with wireless Android Auto and Apple CarPlay, coupled with a 9-speaker JBL system for immersive entertainment.',
    drivingExperience: 'Quiet, refined, and effortless. The electric motor provides instant response in city traffic, while the engine kicks in seamlessly for highway power.',
    ownershipBenefits: ['8 Year Battery Warranty', 'Exceptional Fuel Economy', 'Massive Cabin and Luggage Space'],
    features: ['Ottoman Seats', 'Panoramic Sunroof', 'TSS 3.0', 'Hybrid Powertrain'],
    variants: [{ name: 'ZX Hybrid', price: '₹30.98 Lakh', engine: '2.0L Hybrid', transmission: 'e-CVT', features: ['Sunroof + Tech'] }]
  },
  {
    id: 'hyryder',
    name: 'Urban Cruiser Hyryder',
    tagline: 'Live The Hybrid Life',
    type: 'SUV',
    priceRange: '₹ 11.14 - 20.19 Lakh',
    mileage: '27.97 kmpl',
    engine: '1.5L Self-Charging Hybrid',
    horsepower: '114 HP',
    torque: '122 Nm',
    fuelType: 'Petrol Hybrid',
    seatingCapacity: 5,
    bannerImage: '/assets/cars/hyryder-banner.webp',
    mainImage: '/assets/cars/hyryder-main.webp',
    exteriorImage: '/assets/cars/hyryder-ext.webp',
    interiorImage: '/assets/cars/hyryder-int.webp',
    gallery: ['/assets/cars/hyryder-1.webp'],
    description: 'India’s first strong hybrid SUV in its segment, offering a revolution in efficiency and urban driving.',
    longDescription: 'The Urban Cruiser Hyryder brings Toyota’s world-renowned hybrid technology to the mid-size SUV segment. It is designed for those who want a premium SUV experience without compromising on environmental responsibility or fuel costs. With its silent operation and class-leading mileage, it is the perfect urban explorer.',
    interiorDescription: 'Sophisticated dual-tone dashboard with soft-touch materials. Features like a panoramic sunroof, ventilated front seats, and a 360-degree camera elevate the daily commute into a premium experience.',
    exteriorDescription: 'Elegant and sophisticated SUV design with a crystal acrylic grille and sleek LED signatures. The high hood line and muscular fenders give it a true SUV stance on the road.',
    performanceDescription: 'The self-charging hybrid system allows you to drive in EV mode for a significant portion of your city commute. The smooth e-CVT ensures a gearless, jerk-free driving experience.',
    safetyDescription: 'Equipped with 6 SRS airbags, all-wheel disc brakes, and Vehicle Stability Control. The high-tensile steel body is engineered to provide a safe shell for all passengers.',
    techDescription: 'A color Head-Up Display (HUD) and wireless charging keep you focused and connected. Toyota i-Connect provides 55+ connected features for your convenience.',
    drivingExperience: 'A calm, serene environment inside despite the city noise outside. The transition between electric and petrol power is completely seamless.',
    ownershipBenefits: ['Segment-leading 27.97 kmpl', 'Low Running Costs', 'Environmentally Friendly'],
    features: ['360 Camera', 'Wireless Charging', 'Panoramic Sunroof', 'Hybrid Tech'],
    variants: [{ name: 'V Hybrid AT', price: '₹20.19 Lakh', engine: '1.5L Hybrid', transmission: 'e-CVT', features: ['Top End Spec'] }]
  },
  {
    id: 'glanza',
    name: 'Glanza',
    tagline: 'Hatchin’ Awesome',
    type: 'Hatchback',
    priceRange: '₹ 6.86 - 10.00 Lakh',
    mileage: '22.35 kmpl',
    engine: '1.2L Dual Jet Petrol',
    horsepower: '89 HP',
    torque: '113 Nm',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    bannerImage: '/assets/cars/glanza-banner.webp',
    mainImage: '/assets/cars/glanza-main.webp',
    exteriorImage: '/assets/cars/glanza-ext.webp',
    interiorImage: '/assets/cars/glanza-int.webp',
    gallery: ['/assets/cars/glanza-1.webp'],
    description: 'The cool and tech-loaded hatchback designed for the modern lifestyle.',
    longDescription: 'The Toyota Glanza redefines the premium hatchback segment with its focus on technology, safety, and efficiency. It is the perfect first car for young professionals or an ideal city runabout for families who trust Toyota’s quality and service network.',
    interiorDescription: 'Modern and connected cabin with a 9-inch Smart Playcast infotainment system. The Head-Up Display (HUD) provides vital info without needing to look away from the road, while the 360-degree camera makes parking in tight spots effortless.',
    exteriorDescription: 'Sporty liquid flow design with LED headlamps and signature DRLs. The stylish 16-inch alloy wheels and sleek lines make it stand out in the urban landscape.',
    performanceDescription: 'Refined 1.2L Dual Jet engine with idle start-stop technology to save fuel in heavy traffic. Available in both Manual and AMT transmissions to suit your driving style.',
    safetyDescription: 'Equipped with 6 Airbags, ABS with EBD, and Brake Assist. The high-strength HEARTECT platform provides a secure foundation for every journey.',
    techDescription: 'Hey Toyota Voice Assist allows you to control music and calls with simple voice commands, keeping your hands on the wheel.',
    drivingExperience: 'Nippy and quick, perfect for darting through narrow city lanes. The light steering makes city maneuvers a joy.',
    ownershipBenefits: ['Toyota Warranty Trust', 'High Fuel Efficiency', 'Low Maintenance Cost at Galaxy'],
    features: ['Head-Up Display', '360 Camera', '9-inch Screen', '6 Airbags'],
    variants: [{ name: 'V AMT', price: '₹10.00 Lakh', engine: '1.2L Petrol', transmission: 'AMT', features: ['Top Specs'] }]
  },
  {
    id: 'rumion',
    name: 'Rumion',
    tagline: 'A Spacious Choice',
    type: 'MPV',
    priceRange: '₹ 10.44 - 13.73 Lakh',
    mileage: '20.51 kmpl',
    engine: '1.5L K-Series Petrol',
    horsepower: '103 HP',
    torque: '137 Nm',
    fuelType: 'Petrol/CNG',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/rumion-banner.webp',
    mainImage: '/assets/cars/rumion-main.webp',
    exteriorImage: '/assets/cars/rumion-ext.webp',
    interiorImage: '/assets/cars/rumion-int.webp',
    gallery: ['/assets/cars/rumion-1.webp'],
    description: 'The perfect 7-seater MPV that combines Toyota reliability with family comfort and versatility.',
    longDescription: 'The Toyota Rumion is designed for families who value space and practicality. Whether it is a weekend trip with the extended family or daily errands, the Rumion offers a blend of performance and versatility that makes it a smart choice for the budget-conscious family.',
    interiorDescription: 'Premium wood-finish dashboard with comfortable flexi-seating. The second row can be folded with a single touch to provide easy access to the third row, while the massive luggage space makes holiday road trips a breeze.',
    exteriorDescription: 'Signature chrome-finished grille and LED tail lamps. The compact MPV design makes it easy to park in city environments while offering maximum interior space.',
    performanceDescription: 'Powered by the efficient 1.5L K-series engine with Neo Drive technology for a smooth city drive and improved highway efficiency. Available in both Petrol and CNG options.',
    safetyDescription: 'Dual airbags and ABS with EBD provide the essential safety net for your family. The high-strength body structure is built to protect all 7 occupants.',
    techDescription: 'Smart Playcast touchscreen with smartphone connectivity and steering-mounted controls keeps you in charge of your entertainment.',
    drivingExperience: 'Comfortable and predictable, designed for a relaxed family journey where everyone enjoys the ride.',
    ownershipBenefits: ['Versatile 7-Seater', 'Official CNG Option', 'Legendary Toyota Service Quality'],
    features: ['7-Seater Layout', 'Auto AC', 'Smart Playcast', 'Wood Finish Dash'],
    variants: [{ name: 'V AT', price: '₹13.73 Lakh', engine: '1.5L Petrol', transmission: 'Automatic', features: ['7 Seats Comfort'] }]
  },
  {
    id: 'vellfire',
    name: 'Vellfire',
    tagline: 'A Private Jet on Road',
    type: 'Luxury',
    priceRange: '₹ 1.20 - 1.30 Cr',
    mileage: '19.28 kmpl',
    engine: '2.5L Hybrid',
    horsepower: '193 HP',
    torque: '240 Nm',
    fuelType: 'Petrol Hybrid',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/vellfire-banner.webp',
    mainImage: '/assets/cars/vellfire-main.webp',
    exteriorImage: '/assets/cars/vellfire-ext.webp',
    interiorImage: '/assets/cars/vellfire-int.webp',
    gallery: ['/assets/cars/vellfire-1.webp'],
    description: 'The ultimate expression of executive travel and luxury hospitality on wheels.',
    longDescription: 'Experience Omotenashi at its finest. The Vellfire is India\'s most luxurious MPV, designed for those who demand the privacy and comfort of a business lounge while on the move. It is a masterpiece of craftsmanship and intelligent hybrid technology.',
    interiorDescription: 'VIP Lounge Seats with massage functions, cooling, and power-recline. The dual sunroof and 14-inch rear entertainment screen create an unparalleled private theater experience for the executives in the back.',
    exteriorDescription: 'A commanding stance with massive chrome accents and sliding electric doors. The authoritative presence signals success and prestige at every arrival.',
    performanceDescription: 'Whisper-quiet hybrid powertrain with e-Four 4WD system for a magic-carpet ride quality that makes the road disappear.',
    safetyDescription: 'Advanced TSS and 7 SRS airbags ensure the highest level of protection for the world\'s most important passengers.',
    techDescription: '15-speaker JBL GreenEdge system and multi-color ambient lighting to suit any mood or occasion.',
    drivingExperience: 'Effortless and silent. You forget you are on the road, lost in a world of luxury.',
    ownershipBenefits: ['Ultimate Status Symbol', 'Business Lounge on Wheels', 'Global Luxury Support'],
    features: ['Lounge Seats', 'Dual Sunroof', '14-inch Screen', 'JBL Audio'],
    variants: [{ name: 'Executive', price: '₹1.20 Cr', engine: '2.5L Hybrid', transmission: 'e-CVT', features: ['VIP Lounge'] }]
  },
  {
    id: 'legender',
    name: 'Fortuner Legender',
    tagline: 'Prestige Redefined',
    type: 'SUV',
    priceRange: '₹ 43.66 - 47.64 Lakh',
    mileage: '14.0 kmpl',
    engine: '2.8L Diesel',
    horsepower: '204 HP',
    torque: '500 Nm',
    fuelType: 'Diesel',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/legender-banner.webp',
    mainImage: '/assets/cars/legender-main.webp',
    exteriorImage: '/assets/cars/legender-ext.webp',
    interiorImage: '/assets/cars/legender-int.webp',
    gallery: ['/assets/cars/legender-1.webp'],
    description: 'Aggressive styling meet premium luxury in this sharper, bolder version of the legendary Fortuner.',
    longDescription: 'The Legender is for those who want a sharper edge on the legendary Fortuner foundation. It offers more aggressive aesthetics, exclusive interior themes, and enhanced technology while maintaining the same bulletproof reliability.',
    interiorDescription: 'Exclusive dual-tone maroon and black theme with contrast stitching. Features like a wireless charger, ambient lighting, and dual-zone AC add a touch of modern luxury to the rugged SUV.',
    exteriorDescription: 'Cat-eye LED headlamps and sequential turn signals give it a distinct identity. The sharper split grille and unique 18-inch machine-cut alloy wheels set it apart from anything else on the road.',
    performanceDescription: 'Same legendary 2.8L engine with sportier mapping and a refined drivetrain. Available in both 4x2 and 4x4 configurations to suit your lifestyle.',
    safetyDescription: '7 Airbags and a Panoramic View Monitor for confident maneuvering in tight spots. Built with the same impact-absorbing body structure that Fortuner is famous for.',
    techDescription: 'Sequential LED turn indicators and a kick-sensor powered tailgate for hands-free access to your gear.',
    drivingExperience: 'Commanding, stylish, and authoritative. It turns heads in the city and conquers trails in the wild.',
    ownershipBenefits: ['Exclusive Styling', 'Iconic Fortuner Reliability', 'Premium Resale Value'],
    features: ['Cat-eye LED', 'Sequential Turn', 'Dual Tone Cabin', '4x4 System'],
    variants: [{ name: 'Legender 4x4', price: '₹47.64 Lakh', engine: '2.8L Diesel', transmission: 'Automatic', features: ['4WD Luxury'] }]
  },
  {
    id: 'crysta',
    name: 'Innova Crysta',
    tagline: 'The Legendary Comfort',
    type: 'MPV',
    priceRange: '₹ 19.99 - 26.30 Lakh',
    mileage: '12.0 kmpl',
    engine: '2.4L Diesel',
    horsepower: '150 HP',
    torque: '343 Nm',
    fuelType: 'Diesel',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/crysta-banner.webp',
    mainImage: '/assets/cars/crysta-main.webp',
    exteriorImage: '/assets/cars/crysta-ext.webp',
    interiorImage: '/assets/cars/crysta-int.webp',
    gallery: ['/assets/cars/crysta-1.webp'],
    description: 'The undisputed champion of durability and comfort, trusted by millions for over a decade.',
    longDescription: 'A household name in India, known for its bulletproof reliability and unmatched resale value. The Crysta remains the benchmark for diesel MPVs in the country, preferred by families and fleet owners alike for its low maintenance and high comfort.',
    interiorDescription: 'Rugged yet spacious cabin built for long-distance travel. The easy-to-clean materials and high seating position make it a family favorite for generations.',
    exteriorDescription: 'Classic bold MPV design with modern chrome accents. The robust build quality is evident in every panel, promising years of trouble-free ownership.',
    performanceDescription: 'Proven 2.4L Diesel engine with excellent low-end torque, perfect for hill climbs and heavy loads on the highway.',
    safetyDescription: '7 SRS Airbags and VSC as standard. The GOA body structure provides a safe shell for all occupants across thousands of kilometers.',
    techDescription: 'Standard touchscreen with reliable connectivity and a clear, easy-to-read instrument cluster.',
    drivingExperience: 'A reliable workhorse that never complains, providing a predictable and comfortable drive regardless of the terrain.',
    ownershipBenefits: ['Unbeatable Resale Value', 'Lowest Downtime in Segment', 'Nationwide Parts Availability'],
    features: ['7 Airbags', 'Rear AC Vents', 'One-touch Tumble', 'Eco Mode'],
    variants: [{ name: 'ZX Diesel', price: '₹26.30 Lakh', engine: '2.4L Diesel', transmission: 'Manual', features: ['7 Seater Comfort'] }]
  }
];
