
import { Vehicle } from '../types';

export const VEHICLES: Vehicle[] = [
  {
    id: 'glanza',
    name: 'Glanza',
    tagline: 'Hatchin’ Awesome. The Tech-Loaded Hatch.',
    type: 'Hatchback',
    priceRange: '₹ 6.86 - 10.00 Lakh',
    mileage: '22.35 kmpl',
    engine: '1.2L Dual Jet Petrol',
    horsepower: '89 HP',
    torque: '113 Nm',
    fuelType: 'Petrol / CNG',
    seatingCapacity: 5,
    bannerImage: '/assets/cars/glanza-banner.webp',
    mainImage: '/assets/cars/glanza-main.webp',
    exteriorImage: '/assets/cars/glanza-ext.webp',
    interiorImage: '/assets/cars/glanza-int.webp',
    gallery: ['/assets/cars/glanza-1.webp'],
    description: 'The cool hatchback for the modern world. Loaded with tech, safety, and incredible efficiency.',
    longDescription: 'The Glanza is for the young and the young-at-heart. It redefines the premium hatchback segment by offering features like a Head-Up Display and 360-degree camera usually reserved for luxury sedans. It is the perfect first car for a modern Indian family living in the city.',
    interiorDescription: 'Modern and connected cabin with a 9-inch Smart Playcast. The HUD provides vital info without needing to look away from the road, while "Hey Toyota" voice assist keeps you in control.',
    exteriorDescription: 'Sporty liquid flow design with LED headlamps and signature DRLs. Stylish 16-inch alloy wheels and sleek lines make it stand out in the urban landscape.',
    performanceDescription: 'Refined 1.2L engine with idle start-stop technology to save fuel in heavy traffic. Available in both Manual and AMT transmissions.',
    safetyDescription: '6 Airbags and a 360-degree camera come standard on top variants, offering segment-leading safety and confidence.',
    features: ['HUD', '360 Camera', '9-inch Screen', '6 Airbags', 'Voice Assist'],
    safetyFeatures: ['6 SRS Airbags', 'ABS with EBD', 'Brake Assist', 'ESP with Hill Hold', '360 Camera'],
    variants: [
      { name: 'Glanza E', price: '₹6.86 Lakh', engine: '1.2L Petrol', transmission: 'MT', features: ['Standard Safety'] },
      { name: 'Glanza V AMT', price: '₹10.00 Lakh', engine: '1.2L Petrol', transmission: 'AMT', features: ['Fully Loaded'] }
    ]
  },
  {
    id: 'taisor',
    name: 'Urban Cruiser Taisor',
    tagline: 'Go Daringly Dark. Make Your Way.',
    type: 'SUV',
    priceRange: '₹ 7.74 - 13.04 Lakh',
    mileage: '22.8 kmpl',
    engine: '1.0L Turbo / 1.2L Petrol',
    horsepower: '100 HP',
    torque: '148 Nm',
    fuelType: 'Petrol / CNG',
    seatingCapacity: 5,
    bannerImage: '/assets/banner5.jpg',
    mainImage: '/assets/cars/taisor-main.webp',
    exteriorImage: '/assets/cars/taisor-ext.webp',
    interiorImage: '/assets/cars/taisor-int.webp',
    gallery: ['/assets/cars/taisor-1.webp'],
    description: 'A stylish crossover designed for the modern urban explorer who demands flair and performance.',
    longDescription: 'The Taisor is Toyota\'s latest answer to the sub-compact SUV segment. Blending SUV styling with compact agility, it is the perfect vehicle for navigating the busy streets of Delhi and Noida. Its turbocharged engine options and premium interior make it an attractive choice for young professionals.',
    interiorDescription: 'Premium dual-tone interior with 9-inch Smart Playcast and wireless charger. The Head-Up Display (HUD) and 360-degree camera make navigating urban environments effortless.',
    exteriorDescription: 'Bold crossover styling with twin-slat chrome grille and sporty bumpers. The aero-inspired design is complemented by 16-inch diamond-cut alloy wheels.',
    performanceDescription: 'Experience the thrill of the 1.0L Turbocharged engine producing 100 HP. For those who prioritize efficiency, the 1.2L naturally aspirated engine offers a smooth and refined driving experience.',
    safetyDescription: '6 Airbags, ESP with Hill Hold, and a 360-degree camera provide a safety net for city driving.',
    features: ['Turbo Engine', '360 Camera', 'HUD', '9-inch Touch', 'Wireless Charger'],
    safetyFeatures: ['6 Airbags', 'Electronic Stability Program', 'Hill Hold Assist', 'ABS with EBD', 'Parking Sensors'],
    variants: [
      { name: 'Taisor E MT', price: '₹7.74 Lakh', engine: '1.2L Petrol', transmission: 'MT', features: ['Entry SUV'] },
      { name: 'Taisor V Turbo AT', price: '₹13.04 Lakh', engine: '1.0L Turbo', transmission: 'AT', features: ['Top Spec'] }
    ]
  },
  {
    id: 'hyryder',
    name: 'Urban Cruiser Hyryder',
    tagline: 'The Hybrid Life. Efficiency Redefined.',
    type: 'SUV',
    priceRange: '₹ 11.14 - 20.19 Lakh',
    mileage: '27.97 kmpl',
    engine: '1.5L Strong Hybrid / Neo Drive',
    horsepower: '114 HP',
    torque: '122 Nm',
    fuelType: 'Strong Hybrid / Petrol',
    seatingCapacity: 5,
    bannerImage: '/assets/cars/hyryder-banner.webp',
    mainImage: '/assets/cars/hyryder-main.webp',
    exteriorImage: '/assets/cars/hyryder-ext.webp',
    interiorImage: '/assets/cars/hyryder-int.webp',
    gallery: ['/assets/cars/hyryder-1.webp'],
    description: 'India’s first strong hybrid SUV in its segment. Silent, smooth, and incredibly efficient.',
    longDescription: 'The Hyryder brings Toyota’s world-leading hybrid technology to the heart of the Indian SUV market. It is designed for those who want a premium SUV experience without the high running costs or environmental impact of traditional engines. With its class-leading fuel efficiency, it is the ideal urban explorer.',
    interiorDescription: 'Sophisticated dual-tone dash with soft-touch materials. Features like a panoramic sunroof, ventilated front seats, and a 360-degree camera elevate the daily commute.',
    exteriorDescription: 'Elegant and sophisticated SUV design with a crystal acrylic grille and sleek LED signatures. The high hood line and muscular fenders give it a true SUV stance.',
    performanceDescription: 'Smooth e-CVT and silent hybrid powertrain. Switch to EV mode for a pure electric drive in stop-and-go traffic, maximizing efficiency and serenity.',
    safetyDescription: '6 SRS airbags, all-wheel disc brakes, and Vehicle Stability Control ensure that safety is never compromised.',
    features: ['360 Camera', 'Wireless Charging', 'Sunroof', 'Hybrid Tech', 'Ventilated Seats'],
    safetyFeatures: ['6 SRS Airbags', 'All Wheel Disc Brakes', 'VSC', 'TPMS', 'Hill Hold Assist'],
    variants: [
      { name: 'Hyryder E NeoDrive', price: '₹11.14 Lakh', engine: '1.5L Petrol', transmission: 'MT', features: ['Projector Headlamps'] },
      { name: 'Hyryder V Hybrid', price: '₹20.19 Lakh', engine: '1.5L Strong Hybrid', transmission: 'e-CVT', features: ['Strong Hybrid Tech'] }
    ]
  },
  {
    id: 'rumion',
    name: 'Rumion',
    tagline: 'Experience The Joy of Togetherness.',
    type: 'MPV',
    priceRange: '₹ 10.44 - 13.73 Lakh',
    mileage: '20.51 kmpl',
    engine: '1.5L K-Series Petrol',
    horsepower: '103 HP',
    torque: '137 Nm',
    fuelType: 'Petrol / CNG',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/rumion-banner.webp',
    mainImage: '/assets/cars/rumion-main.webp',
    exteriorImage: '/assets/cars/rumion-ext.webp',
    interiorImage: '/assets/cars/rumion-int.webp',
    gallery: ['/assets/cars/rumion-1.webp'],
    description: 'A spacious and versatile 7-seater MPV built for the modern family.',
    longDescription: 'The Rumion is designed for families who value space, comfort, and Toyota\'s legendary reliability. With its flexible seating and efficient engine, it is the perfect companion for long road trips and city drives alike.',
    interiorDescription: 'Spacious 7-seater cabin with dual-tone finish, premium wood finish dashboard, and automatic climate control. Reclining 2nd and 3rd row seats ensure comfort for everyone.',
    exteriorDescription: 'Distinctive front grille with chrome finish, LED tail lamps, and stylish alloy wheels that give it a premium MPV look.',
    performanceDescription: 'Powered by the 1.5L K-series engine with Neo Drive technology, offering a smooth and responsive drive with exceptional fuel economy.',
    safetyDescription: 'Dual front and side airbags, ABS with EBD, and ISOFIX child seat mounts for family safety.',
    features: ['7 Seater', 'Auto AC', 'Smart Playcast', 'CNG Option', 'Paddle Shifters'],
    safetyFeatures: ['4 Airbags', 'ABS with EBD', 'Hill Hold Assist', 'Rear Sensors'],
    variants: [
      { name: 'Rumion S MT', price: '₹10.44 Lakh', engine: '1.5L Petrol', transmission: 'MT', features: ['Projector Headlamps'] },
      { name: 'Rumion V AT', price: '₹13.73 Lakh', engine: '1.5L Petrol', transmission: 'AT', features: ['Fully Loaded'] }
    ]
  },
  {
    id: 'crysta',
    name: 'Innova Crysta',
    tagline: 'The Legendary King of Comfort.',
    type: 'MPV',
    priceRange: '₹ 19.99 - 26.30 Lakh',
    mileage: '12.0 kmpl',
    engine: '2.4L Diesel',
    horsepower: '150 HP',
    torque: '343 Nm',
    fuelType: 'Diesel',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/crysta-banner.webp',
    mainImage: '/assets/cars/crysta-main.webp',
    exteriorImage: '/assets/cars/crysta-ext.webp',
    interiorImage: '/assets/cars/crysta-int.webp',
    gallery: ['/assets/cars/crysta-1.webp'],
    description: 'The undisputed champion of the Indian roads, known for its bulletproof reliability and unmatched comfort.',
    longDescription: 'Innova Crysta continues to be the preferred choice for those who prioritize long-distance comfort and high resale value. Its powerful diesel engine and robust chassis make it perfect for highway cruising.',
    interiorDescription: 'Premium cabin with wood finish, plush leather seats, and one-touch tumble 2nd row for easy access to the back.',
    exteriorDescription: 'Bold front grille with chrome accents, crystal-cut alloy wheels, and a timeless design that commands respect.',
    performanceDescription: 'Reliable 2.4L Diesel engine delivering strong low-end torque for effortless driving even with a full load.',
    safetyDescription: '7 SRS Airbags, Vehicle Stability Control, and Hill Start Assist for total peace of mind.',
    features: ['7 Airbags', 'Leather Seats', 'Rear AC Control', '8-way Power Seat'],
    safetyFeatures: ['7 SRS Airbags', 'VSC', 'HAC', 'Brake Assist', 'Anti-Theft System'],
    variants: [
      { name: 'Crysta GX MT', price: '₹19.99 Lakh', engine: '2.4L Diesel', transmission: 'MT', features: ['Touchscreen'] },
      { name: 'Crysta ZX MT', price: '₹26.30 Lakh', engine: '2.4L Diesel', transmission: 'MT', features: ['Premium Leather'] }
    ]
  },
  {
    id: 'hycross',
    name: 'Innova Hycross',
    tagline: 'Experience The Future of Family Luxury',
    type: 'MPV',
    priceRange: '₹ 19.77 - 30.98 Lakh',
    mileage: '23.24 kmpl',
    engine: '2.0L TNGA 5th Gen Hybrid',
    horsepower: '184 HP',
    torque: '206 Nm',
    fuelType: 'Strong Hybrid / Petrol',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/hycross-banner.webp',
    mainImage: '/assets/cars/hycross-main.webp',
    exteriorImage: '/assets/cars/hycross-ext.webp',
    interiorImage: '/assets/cars/hycross-int.webp',
    gallery: ['/assets/cars/hycross-1.webp'],
    description: 'The All New Innova Hycross is a perfect blend of SUV stance and the luxury of an executive lounge.',
    longDescription: 'The Hycross redefines family mobility for the modern era. Built on the TNGA-C monocoque platform, it offers car-like handling, exceptional ride comfort, and a level of efficiency that was previously unthinkable in this segment.',
    interiorDescription: 'Featuring the legendary Ottoman seats with power-recline and footrests in the second row. A massive panoramic sunroof and multi-zone climate control create a first-class travel experience.',
    exteriorDescription: 'Muscular SUV-inspired styling with a bold hexagonal grille and sharp LED headlamps. The 18-inch alloy wheels give it a commanding presence.',
    performanceDescription: 'The 5th Gen Self-Charging Strong Hybrid system delivers silent, smooth, and powerful performance while returning an incredible 23.24 kmpl.',
    safetyDescription: 'Equipped with Toyota Safety Sense (TSS) 3.0, offering Dynamic Radar Cruise Control, Lane Trace Assist, and Blind Spot Monitor.',
    features: ['Ottoman Seats', 'Panoramic Sunroof', 'TSS 3.0', 'Hybrid Powertrain', '360 Camera'],
    safetyFeatures: ['6 SRS Airbags', 'Dynamic Radar Cruise Control', 'Lane Trace Assist', 'Blind Spot Monitor', 'All Wheel Disc Brakes'],
    variants: [
      { name: 'Hycross GX Petrol', price: '₹19.77 Lakh', engine: '2.0L Petrol', transmission: 'CVT', features: ['Standard SUV Kit'] },
      { name: 'Hycross ZX Hybrid', price: '₹30.68 Lakh', engine: '2.0L Strong Hybrid', transmission: 'e-CVT', features: ['Ottoman Seats'] }
    ]
  },
  {
    id: 'fortuner',
    name: 'Fortuner',
    tagline: 'Lead The Charge with Authority',
    type: 'SUV',
    priceRange: '₹ 33.43 - 51.44 Lakh',
    mileage: '14.2 kmpl',
    engine: '2.8L Diesel / 2.7L Petrol',
    horsepower: '201 HP',
    torque: '500 Nm',
    fuelType: 'Diesel / Petrol',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/fortuner-banner.webp',
    mainImage: '/assets/cars/fortuner-main.webp',
    exteriorImage: '/assets/cars/fortuner-ext.webp',
    interiorImage: '/assets/cars/fortuner-int.webp',
    gallery: ['/assets/cars/fortuner-1.webp'],
    description: 'The undisputed king of the premium SUV segment in India, known for its bulletproof reliability.',
    longDescription: 'For over a decade, the Fortuner has been the definitive symbol of power on Indian roads. Engineered to conquer everything from urban jungles to the rocky trails of the Himalayas.',
    interiorDescription: 'Premium all-black leather upholstery with ventilated front seats for maximum comfort during long summers. The 11-speaker JBL audio system ensures every drive is entertaining.',
    exteriorDescription: 'Quad-LED headlamps, an aggressive front grille, and 18-inch chrome-finished alloy wheels define its high-status look.',
    performanceDescription: 'The 2.8L Diesel engine is a powerhouse, delivering a massive 500 Nm of torque. Combined with Active Traction Control and a sophisticated 4WD system.',
    safetyDescription: '7 SRS Airbags, Vehicle Stability Control (VSC) with Brake Assist, and Hill Start Assist Control (HAC) ensure your power is always under control.',
    features: ['4x4 System', 'Ventilated Seats', 'JBL Audio', 'Kick Sensor Boot', 'Dual Zone AC'],
    safetyFeatures: ['7 SRS Airbags', 'Active Traction Control', 'Dac (Downhill Assist Control)', 'VSC with BA', 'HAC'],
    variants: [
      { name: 'Fortuner 4x2 MT', price: '₹33.43 Lakh', engine: '2.7L Petrol', transmission: 'Manual', features: ['Classic Performance'] },
      { name: 'Fortuner 4x4 AT', price: '₹42.32 Lakh', engine: '2.8L Diesel', transmission: 'AT', features: ['4WD Mastery'] }
    ]
  },
  {
    id: 'legender',
    name: 'Fortuner Legender',
    tagline: 'Prestige Redefined. Lead with Style.',
    type: 'SUV',
    priceRange: '₹ 43.66 - 47.64 Lakh',
    mileage: '14.0 kmpl',
    engine: '2.8L Turbo Diesel',
    horsepower: '201 HP',
    torque: '500 Nm',
    fuelType: 'Diesel',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/legender-banner.webp',
    mainImage: '/assets/cars/legender-main.webp',
    exteriorImage: '/assets/cars/legender-ext.webp',
    interiorImage: '/assets/cars/legender-int.webp',
    gallery: ['/assets/cars/legender-1.webp'],
    description: 'The Legender is an aggressively styled version of the Fortuner for those who demand ultimate prestige.',
    longDescription: 'With a sharper face, dual-tone exterior, and exclusive interior features, the Legender is built for those who lead by example and style.',
    interiorDescription: 'Exclusive maroon and black dual-tone interior theme, wireless charging, and ambient lighting that sets a premium mood.',
    exteriorDescription: 'Cat-eye LED headlamps with sequential turn indicators, 18-inch machine-cut alloy wheels, and a sharper split grille.',
    performanceDescription: 'The same legendary 2.8L diesel performance but with a focus on refined urban delivery and highway dominance.',
    safetyDescription: 'Full safety suite including 7 airbags and a panoramic view monitor for easy city maneuvering.',
    features: ['Dual Tone Body', 'Sequential Turn Indicators', 'Wireless Charger', 'Kick Sensor Power Back Door'],
    safetyFeatures: ['7 Airbags', 'Panoramic View Monitor', 'VSC', 'HAC'],
    variants: [
      { name: 'Legender 4x2 AT', price: '₹43.66 Lakh', engine: '2.8L Diesel', transmission: 'AT', features: ['Signature Look'] },
      { name: 'Legender 4x4 AT', price: '₹47.64 Lakh', engine: '2.8L Diesel', transmission: 'AT', features: ['All Terrain Prestige'] }
    ]
  },
  {
    id: 'hilux',
    name: 'Hilux',
    tagline: 'Adventure Accomplished. Unbreakable Heritage.',
    type: 'Pickup',
    priceRange: '₹ 30.40 - 37.90 Lakh',
    mileage: '12.0 kmpl',
    engine: '2.8L Turbo Diesel',
    horsepower: '201 HP',
    torque: '500 Nm',
    fuelType: 'Diesel',
    seatingCapacity: 5,
    bannerImage: '/assets/banner3.jpg',
    mainImage: '/assets/cars/hilux-main.webp',
    exteriorImage: '/assets/cars/hilux-ext.webp',
    interiorImage: '/assets/cars/hilux-int.webp',
    gallery: ['/assets/cars/hilux-1.webp'],
    description: 'The world legend of toughness. A lifestyle pickup that conquers every challenge.',
    longDescription: 'The Hilux is the world\'s most famous pickup for a reason. Its indestructible reputation has been earned over decades in the most hostile environments. In India, it serves as the ultimate lifestyle utility vehicle.',
    interiorDescription: 'Durable yet premium. Leather-wrapped cabin with 8-inch touchscreen and dual-zone AC. The seating is ergonomically designed to support occupants over long journeys.',
    exteriorDescription: 'Muscular body lines, 18-inch alloys, and a rear deck built for heavy-duty hauling. The heavy-duty chassis makes it the toughest pickup on the road.',
    performanceDescription: 'Active Traction Control and high-wading depth of 700mm. The 500Nm torque engine ensures power on steep inclines.',
    safetyDescription: '7 Airbags, Vehicle Stability Control, and ABS with EBD come standard, ensuring safety on trails and highways alike.',
    features: ['4x4 System', '700mm Wading', 'Heavy Duty Chassis', 'Leather Cabin', '8-inch Touchscreen'],
    safetyFeatures: ['7 SRS Airbags', 'VSC with BA', 'Hill Start Assist', 'Electronic Drive Control', 'ABS with EBD'],
    variants: [
      { name: 'Hilux STD MT', price: '₹30.40 Lakh', engine: '2.8L Diesel', transmission: 'MT', features: ['4WD Capability'] },
      { name: 'Hilux High AT', price: '₹37.90 Lakh', engine: '2.8L Diesel', transmission: 'AT', features: ['Luxury 4WD'] }
    ]
  },
  {
    id: 'camry',
    name: 'Camry Hybrid',
    tagline: 'The Pinnacle of Sustainable Luxury',
    type: 'Sedan',
    priceRange: '₹ 46.17 Lakh',
    mileage: '19.1 kmpl',
    engine: '2.5L 4-Cylinder Hybrid',
    horsepower: '218 HP',
    torque: '221 Nm',
    fuelType: 'Strong Hybrid',
    seatingCapacity: 5,
    bannerImage: '/assets/banner1.jpg',
    mainImage: '/assets/cars/camry-main.webp',
    exteriorImage: '/assets/cars/camry-ext.webp',
    interiorImage: '/assets/cars/camry-int.webp',
    gallery: ['/assets/cars/camry-1.webp', '/assets/cars/camry-2.webp'],
    description: 'The All New Camry HEV is a masterpiece of luxury and environmental consciousness.',
    longDescription: 'The Toyota Camry Hybrid stands alone as the executive sedan of choice for leaders. Built on the TNGA platform, it offers an exceptionally stable and refined ride quality.',
    interiorDescription: 'A sanctuary of silence. Featuring power-reclining rear seats, 3-zone climate control, and a premium 9-speaker JBL audio system.',
    exteriorDescription: 'Aerodynamic elegance meets authoritative presence. The wide stance and sharp LED headlamps ensure the Camry commands attention.',
    performanceDescription: 'The 2.5L Dynamic Force engine paired with a high-output electric motor delivers 218 combined HP. Acceleration is instantaneous and gearless.',
    safetyDescription: 'Uncompromised protection with 9 SRS Airbags as standard and advanced active safety features.',
    features: ['Reclining Rear Seats', '3-Zone AC', 'Memory Seats', '9 Airbags', 'JBL Audio', 'Ventilated Front Seats'],
    safetyFeatures: ['9 SRS Airbags', 'VSC with Brake Assist', 'Hill Start Assist', 'ISOFIX', 'Parking Sensors'],
    variants: [
      { name: 'Camry Hybrid AT', price: '₹46.17 Lakh', engine: '2.5L Hybrid', transmission: 'e-CVT', features: ['Fully Loaded'] }
    ]
  },
  {
    id: 'vellfire',
    name: 'Vellfire',
    tagline: 'Masterpiece of Hospitality. A Private Jet on Road.',
    type: 'Luxury',
    priceRange: '₹ 1.20 - 1.30 Cr',
    mileage: '19.28 kmpl',
    engine: '2.5L Hybrid',
    horsepower: '193 HP',
    torque: '240 Nm',
    fuelType: 'Strong Hybrid',
    seatingCapacity: 7,
    bannerImage: '/assets/cars/vellfire-banner.webp',
    mainImage: '/assets/cars/vellfire-main.webp',
    exteriorImage: '/assets/cars/vellfire-ext.webp',
    interiorImage: '/assets/cars/vellfire-int.webp',
    gallery: ['/assets/cars/vellfire-1.webp'],
    description: 'The absolute pinnacle of luxury travel. Designed for those who seek the highest form of comfort.',
    longDescription: 'Vellfire offers an unparalleled "Omotenashi" experience. With VIP lounge seats and advanced hybrid tech, it is the ultimate business and luxury MPV.',
    interiorDescription: 'VIP Lounge Seats with massage, ventilation, and memory. Dual sunroofs and a 14-inch rear entertainment screen.',
    exteriorDescription: 'Commanding road presence with massive chrome grille, twin LED headlamps, and sliding electric doors.',
    performanceDescription: 'Silent and efficient 2.5L hybrid system with e-Four AWD for a magic carpet ride quality.',
    safetyDescription: 'Advanced Toyota Safety Sense (TSS) and 7 SRS airbags for complete protection.',
    features: ['Executive Lounge Seats', 'Dual Sunroof', '14-inch Screen', 'JBL Audio', 'Hybrid AWD'],
    safetyFeatures: ['TSS', '7 SRS Airbags', '360 View Monitor', 'Adaptive High Beam'],
    variants: [
      { name: 'Vellfire Hi Grade', price: '₹1.20 Cr', engine: '2.5L Hybrid', transmission: 'e-CVT', features: ['Lounge Luxury'] },
      { name: 'Vellfire VIP Grade', price: '₹1.30 Cr', engine: '2.5L Hybrid', transmission: 'e-CVT', features: ['Max Opulence'] }
    ]
  },
  {
    id: 'lc300',
    name: 'Land Cruiser 300',
    tagline: 'The Absolute King of Earth',
    type: 'Luxury',
    priceRange: '₹ 2.10 Cr',
    mileage: '10.0 kmpl',
    engine: '3.3L V6 Twin-Turbo Diesel',
    horsepower: '304 HP',
    torque: '700 Nm',
    fuelType: 'Diesel',
    seatingCapacity: 5,
    bannerImage: '/assets/banner4.jpg',
    mainImage: '/assets/cars/lc300-main.webp',
    exteriorImage: '/assets/cars/lc300-ext.webp',
    interiorImage: '/assets/cars/lc300-int.webp',
    gallery: ['/assets/cars/lc300-1.webp', '/assets/cars/lc300-2.webp'],
    description: 'Iconic dominance for over 70 years. The LC300 is the ultimate expression of luxury and capability.',
    longDescription: 'The Land Cruiser 300 is not just a vehicle; it is a global icon of authority. Built on the new GA-F platform, it maintains its traditional body-on-frame structure while reducing weight.',
    interiorDescription: 'A sanctuary of world-class luxury. 12.3-inch infotainment, 14-speaker JBL audio, and fingerprint authentication for the engine start.',
    exteriorDescription: 'Massive front grille, triple-LED headlamps, and 20-inch alloy wheels. Optimized for conquering the world\'s toughest terrains.',
    performanceDescription: 'V6 Twin-Turbo producing 700 Nm of torque. The E-KDSS system ensures exceptional on-road comfort and off-road stability.',
    safetyDescription: '10 SRS Airbags and the most advanced Toyota Safety Sense suite for total protection.',
    features: ['E-KDSS', 'Multi Terrain Monitor', 'Fingerprint Auth', '12.3-inch Display', '14 JBL Speakers'],
    safetyFeatures: ['10 SRS Airbags', 'Adaptive High Beam System', 'Lane Departure Alert', 'TSS 3.0', 'Multi Terrain Select'],
    variants: [
      { name: 'Land Cruiser ZX Diesel', price: '₹2.10 Cr', engine: '3.3L V6', transmission: 'AT', features: ['Absolute Mastery'] }
    ]
  }
];
